version: '3'
services:
  node-build:
    container_name: node_common_build
    #指定构建的Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      #工作目录空间
    working_dir: /app
    volumes:
      #jenkins执行的时候，   ./是项目的路径
      - ./:/app
      - /home/liangyu/laughing_zhu_node/project/user_system_fornt:/app/dist
      #这里啊琛哥确认编译之后的文件目录
    command:
      - /bin/sh
      - -c
      - |
        yarn
        npm run build
    #设置环境变量
    networks:
      - node_build
networks:
  node_build:
    driver: bridge
